"""
Freeze what the retiring Python previz says about how things LOOK, so the C++
port can be checked against it once.

    python previz/gen_look_fixture.py

Writes previz/unreal/Tests/look_fixture.json, which the KLights.Look automation
tests read. This is a ONE-TIME port check, not a standing parity guard: the
mirror ball and the beam stand-ins are the renderer's business, and once the
editor driver is retired the C++ is their definition. (The decode is different
-- it is shared with the show, so engine/scene.py stays its definition and
shared/tools/gen_previz_parity.py guards it permanently.)

The driver's pure helpers live in a module that imports `unreal` at the top,
so it is imported here behind a stub of that module rather than copied: a copy
would be a third spelling of the same arithmetic.
"""

from __future__ import annotations

import json
import math
import random
import sys
import types
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "previz" / "unreal" / "Content" / "Python"))

OUT = REPO / "previz" / "unreal" / "Tests" / "look_fixture.json"


def _stub_unreal() -> None:
    """Enough of the `unreal` module for klights_live to import."""
    class _Any:
        def __init__(self, *args, **kwargs):
            pass
    stub = types.ModuleType("unreal")
    stub.__getattr__ = lambda name: _Any        # Transform, Vector, Rotator, ...
    sys.modules["unreal"] = stub


_stub_unreal()
import klights_live as live                       # noqa: E402
from previz import mirrorball as mb               # noqa: E402

V = types.SimpleNamespace


def vec(x, y, z):
    return V(x=x, y=y, z=z)


def unit(rng):
    while True:
        v = [rng.uniform(-1, 1) for _ in range(3)]
        n = math.sqrt(sum(c * c for c in v))
        if 0.1 < n <= 1.0:
            return [c / n for c in v]


def build() -> dict:
    rng = random.Random(20261001)
    data: dict = {"_comment": "Generated by previz/gen_look_fixture.py -- a one-time port check."}

    data["lattice"] = [[r, s, *mb.lattice(r, s)] for r in (50.0, 200.0, 300.0, 450.3, 600.0)
                       for s in (22.0, 45.0)]
    data["fibonacci"] = {str(n): [list(v) for v in mb.fibonacci_normals(n)] for n in (1, 7, 882)}
    seg, rings = mb.lattice(100.0, 22.0)
    data["tiles"] = {"radius": 100.0, "segments": seg, "rings": rings,
                     "tiles": [[*t.normal, *t.east, t.width, t.height]
                               for t in mb.facet_tiles(100.0, seg, rings)]}
    base = mb.fibonacci_normals(50)
    data["spin"] = [{"angle": a, "normals": [list(v) for v in mb.spin(base, a)]}
                    for a in (0.0, 37.5, 359.0)]
    data["facet_size"] = [[r, n, mb.facet_size(r, n)] for r in (100.0, 300.0) for n in (1, 882, 3698)]

    room = (18288.0, 6900.0, 18288.0)
    exits = []
    for _ in range(200):
        origin = [rng.uniform(1, room[0] - 1), rng.uniform(1, room[1] - 1), rng.uniform(1, room[2] - 1)]
        d = unit(rng)
        got = mb.ray_room_exit(tuple(origin), tuple(d), *room)
        exits.append([origin, d, None if got is None else [list(got[0]), list(got[1])]])
    exits.append([[100.0, 100.0, 100.0], [0.0, 0.0, 0.0], None])
    data["room_exit"] = {"room": list(room), "cases": exits}

    ball, radius = (9144.0, 2743.0, 9144.0), 300.0
    hits, lit = [], []
    for _ in range(100):
        origin = [rng.uniform(0, room[0]), rng.uniform(0, room[1]), rng.uniform(0, room[2])]
        to = [b - o for b, o in zip(ball, origin)]
        n = math.sqrt(sum(c * c for c in to))
        d = [c / n + rng.uniform(-0.1, 0.1) for c in to]
        n = math.sqrt(sum(c * c for c in d))
        d = [c / n for c in d]
        half = rng.choice([1.5, 4.0, 5.5, 20.0])
        hits.append([origin, d, half, mb.beam_hits_ball(tuple(origin), tuple(d), half, ball, radius)])
    for distance in (500.0, 4000.0, 6000.0, 12000.0):
        for half in (0.0, 1.5, 4.0, 5.5, 45.0):
            lit.append([distance, half, radius, 882, mb.lit_facets(distance, half, radius, 882)])
    data["beam_hits_ball"] = {"ball": list(ball), "radius": radius, "cases": hits}
    data["lit_facets"] = lit

    normals = mb.reflect_normals(radius)
    corners = [(13216.0, 2971.0, 13216.0), (5072.0, 2971.0, 5072.0), (9144.0, 2971.0, 5072.0)]
    dots = []
    for origin in corners:
        to = [b - o for b, o in zip(ball, origin)]
        n = math.sqrt(sum(c * c for c in to))
        aim = [c / n for c in to]
        off = [aim[0] + 0.004, aim[1] - 0.003, aim[2]]
        n = math.sqrt(sum(c * c for c in off))
        off = [c / n for c in off]
        for direction in (aim, off, [-c for c in aim]):
            for half, stride, angle in ((4.0, 1, 0.0), (1.5, 1, 47.0), (5.5, 3, 123.0)):
                spun = mb.spin(normals, angle)
                got = mb.dots(origin, tuple(direction), half, ball, radius, *room, spun,
                              aperture_mm=mb.APERTURE_MM, stride=stride)
                dots.append({"origin": list(origin), "direction": list(direction), "half": half,
                             "stride": stride, "angle": angle,
                             "dots": [[*d.facet, *d.point, *d.normal, d.throw, d.spot] for d in got]})
    data["dots"] = {"ball": list(ball), "radius": radius, "room": list(room),
                    "count": len(normals), "aperture": mb.APERTURE_MM, "cases": dots}

    # The driver's own helpers, in the Unreal frame it ran them in (cm).
    centre, ball_r = (914.4, 914.4, 274.3), 30.0
    owner = V(ball_centre=centre, ball_radius=ball_r)
    clearance = []
    for _ in range(300):
        origin = [rng.uniform(0, 1828.8), rng.uniform(0, 1828.8), rng.uniform(0, 690.0)]
        to = [c - o for c, o in zip(centre, origin)]
        n = math.sqrt(sum(c * c for c in to))
        spread = rng.choice([0.0, 0.01, 0.03, 0.08, 0.5])
        d = [c / n + rng.uniform(-spread, spread) for c in to]
        n = math.sqrt(sum(c * c for c in d))
        d = [c / n for c in d]
        half = rng.choice([1.5, 4.0, 5.5])
        clearance.append([origin, d, half,
                          live.Live._ball_clearance(owner, vec(*origin), vec(*d), half)])
    clearance.append([[914.4, 914.4, 280.0], [1.0, 0.0, 0.0], 4.0,
                      live.Live._ball_clearance(owner, vec(914.4, 914.4, 280.0), vec(1, 0, 0), 4.0)])
    data["clearance"] = {"centre": list(centre), "radius": ball_r, "cases": clearance}

    planes = []
    for d in ([0.0, 0.0, 1.0], [0.0, 0.0, -1.0], [1.0, 0.0, 0.0]) + tuple(unit(rng) for _ in range(40)):
        planes.append([d, list(live.split_plane(vec(*d)))])
    data["split_plane"] = planes

    data["candela"] = [[lm, beam, live.candela(V(output_beam_deg=beam, output_lumens=lm))]
                       for lm in (48.0, 400.0, 1300.0) for beam in (0.1, 3.0, 8.0, 11.0, 60.0)]
    return data


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(build(), sort_keys=True, separators=(",", ":")) + "\n"
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(text) // 1024} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
