// despacio mobile virtual console -- WebSocket client + renderer.
// Talks directly to QLC+'s built-in web API (ws://<host>:9999/qlcplusWS),
// driving WIDGET ids (never function ids) so the SoloFrame exclusivity mesh
// QLC+ already built keeps working untouched. See despacio/README.md and
// the webui plan for why.
//
// Data comes from two plain globals loaded before this file:
//   window.VC     -- generated by gen_webui_config.py (widgets, dim conflicts)
//   window.LAYOUT -- hand-curated by ui_layout.js (tabs, dimPark, colors)
(function () {
  "use strict";

  var WS_PORT = 9999;
  var FLASH_ACTIONS = { Flash: true };
  var SLIDER_ECHO_SUPPRESS_MS = 250;
  var RECONNECT_MAX_MS = 8000;
  var SEED_SETTLE_MS = 400; // how long we give the getWidgetStatus burst to land before reconciling

  // Classic QLC+ web access only wires its per-widget change signals (the
  // ones that produce "<id>|BUTTON|...", "<id>|SLIDER|...", "<id>|CUE|...")
  // when something has fetched http://<host>:9999/ at least once -- see
  // webaccess.cpp's getButtonHTML/getSliderHTML/getCueListHTML, which
  // `connect()` those signals as a side effect of building that page's HTML.
  // We never load that page (we're a whole separate static site talking
  // straight to the WebSocket), so without this those signals are simply
  // never installed and only the global FUNCTION|<fid> broadcast ever
  // arrives. One harmless, no-cors, fire-and-forget fetch -- ONCE per page
  // load, not per reconnect, since repeated getVCHTML() calls stack
  // duplicate Qt connections and duplicate every future broadcast -- arms
  // them for the rest of the session. Kill switch via localStorage in case
  // this ever misbehaves against a different QLC+ build.
  var ARM_PUSH_UPDATES = localStorage.getItem("despacio.armPush") !== "0";
  var pushArmed = false;

  // ------------------------------------------------------------- lookups

  var byId = new Map();
  var byCaption = new Map();
  var widgetsByFunctionId = new Map(); // functionId -> [button widgets bound to it]
  VC.widgets.forEach(function (w) {
    byId.set(w.id, w);
    byCaption.set(w.caption, w);
    if (w.kind === "button" && w.functionId != null) {
      var list = widgetsByFunctionId.get(w.functionId);
      if (!list) widgetsByFunctionId.set(w.functionId, list = []);
      list.push(w);
    }
  });

  // CueLists watch every step's underlying function id too, so a running
  // step (not just the chaser itself) can be resolved back to a cuelist.
  var cuelistsByFunctionId = new Map(); // functionId -> [cuelist widgets]
  function addCuelistWatch(fid, widget) {
    var list = cuelistsByFunctionId.get(fid);
    if (!list) cuelistsByFunctionId.set(fid, list = []);
    if (list.indexOf(widget) === -1) list.push(widget);
  }
  VC.widgets.forEach(function (w) {
    if (w.kind !== "cuelist") return;
    if (w.chaserId != null) addCuelistWatch(w.chaserId, w);
    w.steps.forEach(function (s) { addCuelistWatch(s.functionId, w); });
  });

  var placedCaptions = new Set();
  LAYOUT.tabs.forEach(function (tab) {
    tab.sections.forEach(function (s) { s.items.forEach(function (c) { placedCaptions.add(c); }); });
  });
  (LAYOUT.header.items || []).forEach(function (c) { placedCaptions.add(c); });

  var unsortedCaptions = VC.widgets
    .map(function (w) { return w.caption; })
    .filter(function (c) { return !placedCaptions.has(c); });

  // ---------------------------------------------------------------- state

  // widgetId -> live value. Buttons: 0/127/255. Sliders: raw value in the
  // widget's [low, high]. Populated by QLC+API getWidgetStatus replies and
  // kept current by push messages.
  var state = new Map();
  var sliderLocalUntil = new Map(); // widgetId -> timestamp; suppress echoes while dragging

  // functionId -> true, for every function currently running. THIS remains
  // the primary live-update signal regardless of ARM_PUSH_UPDATES: without
  // arming, this QLC+ build broadcasts nothing per-widget at all (pressing a
  // button only ever produces "FUNCTION|<fid>|Running"/"Stopped" frames), and
  // even WITH arming, a function can be started by a *different* widget than
  // the one on screen (the hidden SoloFrame mirror mesh) with no
  // "<id>|BUTTON|..." for THIS widget at all -- FUNCTION is keyed by function
  // ID, which every mirror shares, so it's the only signal that reaches every
  // widget bound to that function. The seed reply and (once armed) the
  // "<id>|BUTTON|..." push still set a button's own active state directly
  // from ITS reported value; setButtonActive() folds both paths into this
  // set so they can't disagree.
  var runningFunctions = new Set();

  var ws = null;
  var reconnectDelay = 500;

  // True while the getWidgetStatus seed burst from onOpen() is still landing.
  // Button/slider state and repaints happen normally during this window, but
  // MH-Dim-park side effects (which would otherwise fire once per widget as
  // the burst arrives, each write based on a partial view of what's running)
  // and the show banners (same problem) are deferred until finishSeeding()
  // reconciles once against the settled state -- see onButtonActiveChanged.
  var seeding = false;
  var seedTimer = null;
  var seededWidgetIds = new Set(); // reset each onOpen(); see finishSeeding()'s mismatch check

  // ----------------------------------------------------------- WS connect

  // Defaults to serving-host-equals-QLC+-host (the common case: serve.py and
  // QLC+ running on the same machine), which wsUrl() previously assumed
  // unconditionally with nothing to override it. ?qlc=<host> in the URL
  // remembers itself in localStorage, so a phone bookmarked once with the
  // override keeps working without retyping it every load.
  function qlcHost() {
    var q = new URLSearchParams(location.search).get("qlc");
    if (q) {
      localStorage.setItem("despacio.qlcHost", q);
      return q;
    }
    return localStorage.getItem("despacio.qlcHost") || location.hostname;
  }

  function wsUrl() {
    return "ws://" + qlcHost() + ":" + WS_PORT + "/qlcplusWS";
  }

  function connect() {
    setConnState("connecting");
    ws = new WebSocket(wsUrl());
    ws.onopen = onOpen;
    ws.onmessage = onMessage;
    ws.onclose = onClose;
    ws.onerror = function () { /* onclose follows */ };
  }

  function onOpen() {
    reconnectDelay = 500;
    setConnState("connected");
    seeding = true;
    seededWidgetIds.clear();
    if (seedTimer) clearTimeout(seedTimer);
    // Seed state for every real widget so the UI reflects reality on load,
    // not just whatever changes after we connect.
    VC.widgets.forEach(function (w) {
      send("QLC+API|getWidgetStatus|" + w.id);
    });
    // Arm QLC+'s per-widget push signals (see ARM_PUSH_UPDATES above) --
    // once per page load, not per reconnect.
    if (ARM_PUSH_UPDATES && !pushArmed) {
      pushArmed = true;
      fetch("http://" + qlcHost() + ":" + WS_PORT + "/", { mode: "no-cors" })
        .catch(function () {});
    }
    seedTimer = setTimeout(finishSeeding, SEED_SETTLE_MS);
  }

  // Called once the seed burst has had time to land (or on close, so a
  // dropped connection mid-burst doesn't leave `seeding` stuck true).
  // Reconciles MH Dim park state and the show banners exactly once against
  // the settled picture, instead of once per widget as replies trickle in.
  function finishSeeding() {
    if (!seeding) return;
    seeding = false;
    // If QLC+ answered for far fewer widgets than this generated config
    // expects, the loaded workspace doesn't match ui_config.js -- e.g.
    // despacio.qxw was edited/reloaded in QLC+ without re-running
    // gen_webui_config.py. Previously there was no way to tell this from a
    // partially-broken UI short of noticing individual missing controls.
    var missing = VC.widgets.length - seededWidgetIds.size;
    if (missing > 0) {
      showConfigMismatch(missing);
    } else {
      clearConfigMismatch();
    }
    updateMhDimPark();
    updateBanners();
  }

  function showConfigMismatch(missingCount) {
    var badge = document.getElementById("configBadge");
    if (!badge) return;
    badge.hidden = false;
    badge.innerHTML = "";
    badge.appendChild(el("span", null,
      missingCount + " of " + VC.widgets.length + " widget(s) got no reply from QLC+ -- the " +
      "loaded despacio.qxw may not match this generated config. Re-run gen_webui_config.py " +
      "(or restart the phone page once QLC+ has the right workspace loaded)."));
    var btn = el("button", null, "Dismiss");
    btn.addEventListener("click", clearConfigMismatch);
    badge.appendChild(btn);
  }
  function clearConfigMismatch() {
    var badge = document.getElementById("configBadge");
    if (badge) badge.hidden = true;
  }

  function onClose() {
    setConnState("disconnected");
    ws = null;
    if (seedTimer) { clearTimeout(seedTimer); seedTimer = null; }
    seeding = false;
    setTimeout(connect, reconnectDelay);
    reconnectDelay = Math.min(reconnectDelay * 1.6, RECONNECT_MAX_MS);
  }

  function send(msg) {
    if (ws && ws.readyState === WebSocket.OPEN) { ws.send(msg); return; }
    // Previously a silent no-op -- a press while disconnected looked
    // identical to a press that worked, with nothing to say otherwise
    // besides the easy-to-miss header dot.
    showToast("Not connected to QLC+ -- that press did nothing");
  }

  var connState = "disconnected";

  function setConnState(s) {
    connState = s;
    var dot = document.getElementById("connDot");
    dot.className = "conn-dot " + s;
    dot.title = s;
    updateBanners();
  }

  var toastTimer = null;
  function showToast(msg) {
    var t = document.getElementById("toast");
    if (!t) return;
    t.textContent = msg;
    t.hidden = false;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(function () { t.hidden = true; }, 2200);
  }

  // ------------------------------------------------------------- messages

  function onMessage(evt) {
    var data = evt.data;
    if (!data) return;

    if (data.indexOf("QLC+API|getWidgetStatus|") === 0) {
      var parts = data.split("|");
      // QLC+API|getWidgetStatus|<id>|<value...>
      var seedId = parseInt(parts[2], 10);
      seededWidgetIds.add(seedId);
      applyStatus(seedId, parts.slice(3));
      return;
    }
    if (data.indexOf("FUNCTION|") === 0) {
      // "FUNCTION|<fid>|Running" / "FUNCTION|<fid>|Stopped" -- sent
      // regardless of ARM_PUSH_UPDATES, and the only signal that reaches
      // every widget bound to a function (see the runningFunctions comment
      // above). This drives button active state AND cuelist step
      // highlighting.
      var fparts = data.split("|");
      var fid = parseInt(fparts[1], 10);
      var running = fparts[2] === "Running";
      if (Number.isNaN(fid)) return;
      if (running) runningFunctions.add(fid); else runningFunctions.delete(fid);
      (widgetsByFunctionId.get(fid) || []).forEach(function (w) { setButtonActive(w, running); });
      (cuelistsByFunctionId.get(fid) || []).forEach(renderCueList);
      return;
    }

    var parts = data.split("|");
    var idOrTag = parts[0];
    if (idOrTag === "GM_VALUE" || idOrTag === "POLL") return;

    var id = parseInt(idOrTag, 10);
    if (Number.isNaN(id)) return;
    applyStatus(id, parts.slice(1));
  }

  // Single source of truth for "is this button lit" -- updates state,
  // runningFunctions (so seeding and live FUNCTION events agree), fires the
  // dim-park/banner side effects, and repaints. Called from both the seed
  // path (getWidgetStatus) and the live path (FUNCTION broadcasts), plus
  // the "<id>|BUTTON|..." fallback below if a QLC+ build ever sends it.
  function setButtonActive(widget, active) {
    var wasActive = state.get(widget.id) === 255;
    state.set(widget.id, active ? 255 : 0);
    if (widget.functionId != null) {
      if (active) runningFunctions.add(widget.functionId);
      else runningFunctions.delete(widget.functionId);
    }
    renderWidget(widget);
    if (active !== wasActive) onButtonActiveChanged(widget, active);
  }

  function applyStatus(id, rest) {
    var widget = byId.get(id);
    if (!widget) return;
    var tag = rest[0];

    if (widget.kind === "button") {
      // Either "<id>|BUTTON|<0|127|255>" (push -- only sent once
      // ARM_PUSH_UPDATES has armed it, see the top-of-file comment) or the
      // getWidgetStatus reply "<id>|<0|127|255>" (tag itself IS the value).
      // 127 is QLC+'s "Monitoring" state -- a button whose function is
      // running but wasn't started by THIS button (the SoloFrame mesh
      // again). Treated as active: v !== 0, not v === 255.
      var raw = tag === "BUTTON" ? rest[1] : tag;
      var v = parseInt(raw, 10);
      if (Number.isNaN(v)) return;
      setButtonActive(widget, v !== 0);
      return;
    }

    if (widget.kind === "slider") {
      var val = tag === "SLIDER" ? parseInt(rest[1], 10) : parseInt(tag, 10);
      if (Number.isNaN(val)) return;
      var suppressUntil = sliderLocalUntil.get(id) || 0;
      if (Date.now() < suppressUntil) return; // we just moved it locally, ignore the echo
      state.set(id, val);
      renderWidget(widget);
      if (widget.caption === "MH Dim") onMhDimExternalChange(val);
      return;
    }

    if (widget.kind === "cuelist") {
      // "<id>|PLAY|<index>" / "<id>|STOP" is the getWidgetStatus seed reply
      // shape. "<id>|CUE|<index>" is the live push (only sent once
      // ARM_PUSH_UPDATES has armed it) fired as the chaser steps -- without
      // arming, step advances are picked up from FUNCTION broadcasts instead
      // (see renderCueList()'s runningFunctions-based fallback), which can't
      // tell WHICH step is current, only that the cuelist's chaser is
      // running at all.
      if (tag === "PLAY" || tag === "STOP") {
        state.set(id, { playing: tag === "PLAY", index: tag === "PLAY" ? parseInt(rest[1], 10) : -1 });
        renderCueList(widget);
      } else if (tag === "CUE") {
        var idx = parseInt(rest[1], 10);
        if (!Number.isNaN(idx)) {
          state.set(id, { playing: true, index: idx });
          renderCueList(widget);
        }
      }
      return;
    }
  }

  // ------------------------------------------------------- button actions

  function pressToggle(widget) {
    var active = state.get(widget.id) === 255;
    send(widget.id + "|" + (active ? 0 : 1));
    // Buttons with no bound function (Blackout is the only one in this show)
    // never produce a FUNCTION broadcast to confirm the flip, and without
    // ARM_PUSH_UPDATES there's no BUTTON push either -- nothing would ever
    // correct our state, so the NEXT press would re-send the same direction
    // again instead of toggling back. Optimistically flip local state for
    // just this case; everything else still waits for the real signal.
    if (widget.functionId == null) setButtonActive(widget, !active);
  }

  // Tracks every Flash-action widget (Strobe, White Bump, Reset Heads) that's
  // currently held down at 255, so a backgrounded tab or a lost pointer can't
  // leave it stuck ON -- see releaseAllHeldFlash() below. pointerup/
  // pointercancel/pointerleave (wired in renderTile()) cover the ordinary
  // release paths; this covers the ones a pointer event can't reach.
  var heldFlashWidgets = new Set();

  function flashDown(widget) {
    heldFlashWidgets.add(widget);
    send(widget.id + "|255");
    var el = widgetEl(widget.id);
    if (el) el.classList.add("pressed");
  }
  function flashUp(widget) {
    heldFlashWidgets.delete(widget);
    send(widget.id + "|0");
    var el = widgetEl(widget.id);
    if (el) el.classList.remove("pressed");
  }
  function releaseAllHeldFlash() {
    Array.from(heldFlashWidgets).forEach(flashUp);
  }

  // ---------------------------------------------------------- slider send

  // Single path for every slider write this client originates -- always
  // stamps sliderLocalUntil first, so the SLIDER push QLC+ echoes back
  // (once ARM_PUSH_UPDATES is on) is recognised as our own and suppressed by
  // applyStatus's slider branch, instead of being mistaken for an external
  // move and tripping onMhDimExternalChange's manual-override logic. Used by
  // direct user drags (sliderInput) AND the MH-Dim-park writes below, which
  // used to call send() directly and would otherwise self-trigger exactly
  // that override the moment push updates were armed.
  function sendSliderValue(widget, v) {
    sliderLocalUntil.set(widget.id, Date.now() + SLIDER_ECHO_SUPPRESS_MS);
    state.set(widget.id, v);
    send(widget.id + "|" + v);
    renderWidget(widget);
  }

  // A fast drag fires `input` at display refresh rate; sending every one of
  // those straight to the socket floods it over Wi-Fi for no visible gain.
  // Coalesced per widget to one send per animation frame -- the dragged
  // widget's own paint still happens immediately below, so the UI never
  // lags the finger even though the network write does.
  var sliderPendingValue = new Map(); // widgetId -> latest value waiting to be sent
  var sliderRafScheduled = new Set(); // widgetIds with a queued rAF flush

  function sliderInput(widget, rawValue) {
    var v = Math.round(rawValue);
    state.set(widget.id, v);
    renderWidget(widget);
    sliderPendingValue.set(widget.id, v);
    if (!sliderRafScheduled.has(widget.id)) {
      sliderRafScheduled.add(widget.id);
      requestAnimationFrame(function () {
        sliderRafScheduled.delete(widget.id);
        var latest = sliderPendingValue.get(widget.id);
        sliderPendingValue.delete(widget.id);
        sendSliderValue(widget, latest);
      });
    }
    if (widget.caption === "MH Dim") onMhDimManualMove();
  }

  // ----------------------------------------------------------- rendering

  function widgetEl(id) { return document.querySelector('[data-widget-id="' + id + '"]'); }

  function el(tag, cls, text) {
    var e = document.createElement(tag);
    if (cls) e.className = cls;
    if (text != null) e.textContent = text;
    return e;
  }

  function pct(widget) {
    var v = state.has(widget.id) ? state.get(widget.id) : widget.value;
    var span = widget.high - widget.low || 1;
    return Math.max(0, Math.min(100, ((v - widget.low) / span) * 100));
  }

  function renderTile(widget, extraClass) {
    var caption = widget.caption;
    var isFlash = FLASH_ACTIONS[widget.action] === true;
    var swatchColor = LAYOUT.colors && LAYOUT.colors[caption];
    var cls = isFlash ? "w-flash" : (swatchColor ? "w-swatch" : "w-tile");
    if (extraClass) cls += " " + extraClass;
    var b = el("button", cls, caption);
    b.setAttribute("data-widget-id", widget.id);
    if (swatchColor) b.style.background = swatchColor;
    var aimWarn = aimWarningsByCaption[caption];
    if (aimWarn) {
      // Corner marker only (see styles.css's [data-aim-warn]) -- the tile's
      // normal action still fires below; this just ALSO surfaces the aim
      // reachability detail via aimBadge, same passive-alongside-the-real-
      // action idea as MH Dim's park badge.
      b.setAttribute("data-aim-warn", aimWarn.severity);
      b.addEventListener("click", function () { showAimBadge(aimWarn); });
    }
    if (isFlash) {
      b.addEventListener("pointerdown", function (e) { e.preventDefault(); flashDown(widget); });
      ["pointerup", "pointercancel", "pointerleave"].forEach(function (evt) {
        b.addEventListener(evt, function () { flashUp(widget); });
      });
    } else {
      b.addEventListener("click", function () { pressToggle(widget); });
    }
    // Initial state isn't painted here -- the element isn't in the DOM yet
    // (widgetEl() would find nothing). renderTab() does a full repaint pass
    // over VC.widgets after all sections are appended.
    return b;
  }

  function renderSlider(widget, opts) {
    opts = opts || {};
    var wrap = el("div", "w-slider-wrap" + (opts.knob ? " w-knob-wrap" : ""));
    var label = el("div", "w-slider-label");
    var name = el("span", null, opts.shortLabel || widget.caption);
    var val = el("span", "val");
    label.appendChild(name);
    label.appendChild(val);
    var input = document.createElement("input");
    input.type = "range";
    input.className = "w-slider";
    input.min = widget.low;
    input.max = widget.high;
    input.value = state.has(widget.id) ? state.get(widget.id) : widget.value;
    input.setAttribute("data-widget-id", widget.id);
    input.addEventListener("input", function () { sliderInput(widget, Number(input.value)); });
    wrap.appendChild(label);
    wrap.appendChild(input);
    if (opts.nudge) {
      // Fine-aim calibration on the Setup tab's Pan/Tilt knobs: a horizontal
      // range input spanning the full 0-255 DMX range in ~80px is roughly 3
      // units per pixel of drag, unusable for the one tab whose entire job
      // is precise aiming. +/-1 for last-degree trim, +/-5 for faster travel.
      var nudgeRow = el("div", "w-knob-nudge");
      [-5, -1, 1, 5].forEach(function (delta) {
        var btn = el("button", null, (delta > 0 ? "+" : "−") + Math.abs(delta));
        btn.addEventListener("click", function () {
          var cur = state.has(widget.id) ? state.get(widget.id) : widget.value;
          var next = Math.max(widget.low, Math.min(widget.high, cur + delta));
          input.value = next;
          sliderInput(widget, next);
        });
        nudgeRow.appendChild(btn);
      });
      wrap.appendChild(nudgeRow);
    }
    return wrap;
  }

  function renderCueListWidget(widget) {
    var wrap = el("div", "cuelist");
    wrap.setAttribute("data-widget-id", widget.id);
    // gen_webui_config.py's resolve_aim_warnings() resolves CueList widgets
    // too (Night, in this show, has the widest aggregate of any widget), but
    // the marker used to only ever get attached in renderTile() -- a cue
    // list has no tile to attach it to, so the warning was silently
    // unreachable from the phone. A dedicated small button rather than a
    // corner overlay (like renderTile()'s [data-aim-warn]) because a
    // transport/step click listener on the whole wrap would pop the badge on
    // every PREV/STOP/GO/step press too.
    var aimWarn = aimWarningsByCaption[widget.caption];
    if (aimWarn) {
      var marker = el("button", "cuelist-aim-warn", "⚠ aim");
      marker.setAttribute("data-aim-warn", aimWarn.severity);
      marker.addEventListener("click", function () { showAimBadge(aimWarn); });
      wrap.appendChild(marker);
    }
    var transport = el("div", "cuelist-transport");
    var prev = el("button", null, "PREV");
    var stop = el("button", null, "STOP");
    var go = el("button", "go", "GO");
    var play = el("button", null, "▶ / II");
    prev.addEventListener("click", function () { send(widget.id + "|PREV"); });
    stop.addEventListener("click", function () { send(widget.id + "|STOP"); });
    go.addEventListener("click", function () { send(widget.id + "|NEXT"); });
    play.addEventListener("click", function () { send(widget.id + "|PLAY"); });
    [prev, stop, go, play].forEach(function (b) { transport.appendChild(b); });
    var steps = el("div", "cuelist-steps");
    widget.steps.forEach(function (s, i) {
      var row = el("div", "cuelist-step");
      row.setAttribute("data-step-index", i);
      var nm = el("span", null, s.name || ("Step " + i));
      var hold = el("span", "hold", s.holdMs == null ? "hold" : Math.round(s.holdMs / 1000) + "s");
      row.appendChild(nm);
      row.appendChild(hold);
      row.addEventListener("click", function () { send(widget.id + "|STEP|" + i); });
      steps.appendChild(row);
    });
    wrap.appendChild(transport);
    wrap.appendChild(steps);
    return wrap;
  }

  function renderTempoWidget(widget) {
    // QLC+'s SpeedDial has no feedback path at all: getWidgetStatus doesn't
    // handle SpeedWidget (falls through to a hardcoded "0"), and this build
    // never broadcasts anything when SPEED_UP/SPEED_DOWN/SPEED_TIME change
    // the dial (confirmed by sniffing the raw socket -- sending SPEED_DOWN
    // produces zero reply traffic). So the client has to be the sole source
    // of truth for what the current bar length is: every control here
    // tracks `currentMs` locally and always sends an ABSOLUTE
    // "id|SPEED_TIME|<ms>" rather than a relative SPEED_UP/SPEED_DOWN,
    // because a relative nudge we can't observe the result of would just
    // drift out of sync with the readout (which is exactly what "÷2/×2
    // doesn't work" was -- the commands almost certainly did reach QLC+,
    // there was just no way to show they'd done anything).
    var wrap = el("div", "tempo-wrap");
    var pad = el("button", "tempo-pad", "TAP");
    var readout = el("div", "tempo-readout");
    var nudge = el("div", "tempo-nudge");
    var down = el("button", null, "÷2 (slower)");
    var up = el("button", null, "×2 (faster)");
    nudge.appendChild(down);
    nudge.appendChild(up);

    var manualRow = el("div", "tempo-manual");
    var manualInput = document.createElement("input");
    manualInput.type = "number";
    manualInput.className = "tempo-manual-input";
    manualInput.min = widget.minMs;
    manualInput.max = widget.maxMs;
    manualInput.step = 10;
    var manualLabel = el("span", null, "ms/bar");
    manualRow.appendChild(manualInput);
    manualRow.appendChild(manualLabel);

    var currentMs = widget.timeMs;

    function clamp(ms) { return Math.round(Math.max(widget.minMs, Math.min(widget.maxMs, ms))); }

    function setMs(ms, send_) {
      currentMs = clamp(ms);
      var bpm = Math.round(60000 / currentMs);
      readout.innerHTML = "";
      readout.appendChild(el("b", null, currentMs + " ms/bar"));
      readout.appendChild(document.createTextNode("  ·  ~" + bpm + " BPM"));
      manualInput.value = currentMs;
      if (send_) send(widget.id + "|SPEED_TIME|" + currentMs);
    }
    setMs(currentMs, false);

    // TAP_STALE_MS: walking away mid-sequence and tapping again later used to
    // splice a multi-second gap in as if it were a real interval -- reset
    // the sequence instead once the gap since the last tap is implausibly
    // long for an actual tap tempo (longer than the widest bar this dial
    // supports).
    var TAP_STALE_MS = widget.maxMs;
    var taps = [];
    pad.addEventListener("click", function () {
      var now = performance.now();
      if (taps.length && now - taps[taps.length - 1] > TAP_STALE_MS) taps.length = 0;
      taps.push(now);
      if (taps.length > 4) taps.shift();
      if (taps.length >= 2) {
        var intervals = [];
        for (var i = 1; i < taps.length; i++) intervals.push(taps[i] - taps[i - 1]);
        // MEAN, not median -- with an even count of intervals (3 taps -> 2
        // intervals is the common case) the median picks the sorted array's
        // upper-middle element, i.e. always the LARGER of the two, biasing
        // every tap sequence slow instead of averaging them.
        var mean = intervals.reduce(function (a, b) { return a + b; }, 0) / intervals.length;
        setMs(mean, true);
      }
    });
    // ÷2 = half-time (everything feels half as fast) = the bar takes TWICE
    // as long = ms DOUBLES. ×2 = double-time = ms HALVES. See README's
    // Tempo dial section ("Nudge -/+ | 228/229 | /2 / x2 -- half-time /
    // double-time") -- these buttons match that semantic, not a literal
    // "divide the ms by 2" reading of the label.
    down.addEventListener("click", function () { setMs(currentMs * 2, true); });
    up.addEventListener("click", function () { setMs(currentMs / 2, true); });
    manualInput.addEventListener("change", function () {
      var v = Number(manualInput.value);
      if (!Number.isNaN(v) && v > 0) setMs(v, true);
    });

    wrap.appendChild(pad);
    wrap.appendChild(readout);
    wrap.appendChild(nudge);
    wrap.appendChild(manualRow);
    return wrap;
  }

  function renderWidget(widget) {
    var el2 = widgetEl(widget.id);
    if (!el2) return;
    if (widget.kind === "button") {
      var active = state.get(widget.id) === 255;
      el2.classList.toggle("active", active && !FLASH_ACTIONS[widget.action]);
    } else if (widget.kind === "slider") {
      var v = state.has(widget.id) ? state.get(widget.id) : widget.value;
      if (el2.tagName === "INPUT") {
        el2.value = v;
        el2.style.setProperty("--fill", pct(widget) + "%");
        var label = el2.parentElement.querySelector(".val");
        if (label) label.textContent = widget.displayStyle === "Percentage"
          ? Math.round(pct(widget)) + "%" : v;
      }
    }
  }

  // The chaser's currently-running STEP function is the most reliable
  // signal for "which row is current" -- it's driven by the same FUNCTION
  // broadcasts that arrive with or without ARM_PUSH_UPDATES (see the
  // runningFunctions comment up top), and unlike the seeded/pushed index it
  // can never point at a step the chaser has already moved past. Only falls
  // back to state's index (from the getWidgetStatus seed or a CUE push) when
  // no step's function is currently running -- e.g. right after a reload,
  // before the first FUNCTION broadcast for this cuelist has arrived.
  function cueListCurrentIndex(widget) {
    for (var i = 0; i < widget.steps.length; i++) {
      if (runningFunctions.has(widget.steps[i].functionId)) return i;
    }
    var st = state.get(widget.id);
    return st && st.playing ? st.index : -1;
  }

  function renderCueList(widget) {
    var wrap = widgetEl(widget.id);
    if (!wrap) return;
    var idx = cueListCurrentIndex(widget);
    wrap.querySelectorAll(".cuelist-step").forEach(function (row) {
      var i = Number(row.getAttribute("data-step-index"));
      row.classList.toggle("current", i === idx);
    });
  }

  function renderSection(section) {
    var card = el("div", "section");
    // ui_layout.js's `badge: 'park-target'` on MH Dim's section used to be
    // dead config -- declared but never read by any renderX() branch below.
    var title = section.title;
    if (title && section.badge === "park-target") title += "  ·  auto-park target";
    if (title) card.appendChild(el("div", "section-title", title));

    if (section.style === "cuelist" || section.style === "tempo") {
      section.items.forEach(function (caption) {
        var w = byCaption.get(caption);
        if (!w) return;
        card.appendChild(section.style === "cuelist" ? renderCueListWidget(w) : renderTempoWidget(w));
      });
      return card;
    }

    if (section.style === "slider" || section.style === "slider-lg") {
      if (section.style === "slider-lg") card.classList.add("slider-lg");
      section.items.forEach(function (caption) {
        var w = byCaption.get(caption);
        if (w) card.appendChild(renderSlider(w));
      });
      return card;
    }

    if (section.style === "knob") {
      var kgrid = el("div", "grid knob-grid");
      section.items.forEach(function (caption) {
        var w = byCaption.get(caption);
        if (w) kgrid.appendChild(renderSlider(w, { knob: true, nudge: true, shortLabel: caption.replace(/^(Pan|Tilt) /, "") }));
      });
      card.appendChild(kgrid);
      return card;
    }

    // tile / tile-lg / swatch / flash
    var grid = el("div", "grid" + (section.style === "tile-lg" ? " grid-lg" : ""));
    section.items.forEach(function (caption) {
      var w = byCaption.get(caption);
      if (!w) return;
      // (renderTile()'s extraClass param was passed "" vs null here --
      // both falsy, so it never actually added a class either way. The
      // [data-dims] attribute below is what the CSS marker keys off.)
      var tile = renderTile(w);
      if (section.badge === "dims") tile.setAttribute("data-dims", "1");
      grid.appendChild(tile);
    });
    card.appendChild(grid);
    return card;
  }

  function renderTab(tab) {
    var main = document.getElementById("main");
    main.innerHTML = "";
    tab.sections.forEach(function (s) { main.appendChild(renderSection(s)); });
    if (tab.id === "setup") {
      var note = el("div", "setup-note",
        "Sideways mount: Pan knobs move heads UP/DOWN, Tilt knobs move heads LEFT/RIGHT. " +
        "Manual aim only works while no position preset or EFX is running -- routines rewrite pan/tilt every tick.");
      main.insertBefore(note, main.firstChild);
      main.appendChild(renderAutoParkToggle());
      main.appendChild(renderGeneratedFooter());
    }
    if (tab.id === "show" && unsortedCaptions.length) {
      main.appendChild(renderUnsorted());
    }
    // repaint everything now that it's in the DOM
    VC.widgets.forEach(renderWidget);
    VC.widgets.filter(function (w) { return w.kind === "cuelist"; }).forEach(renderCueList);
  }

  function renderUnsorted() {
    var card = el("div", "section unsorted");
    card.appendChild(el("div", "section-title", "Unsorted (new in QLC+, not placed in ui_layout.js yet)"));
    // Buttons share one grid; sliders/cuelists/speeddials each need their own
    // full-width row, so they're appended straight to the card below instead.
    // Previously anything that wasn't a button was dropped silently here --
    // a new slider or cue list added in QLC+ would vanish with only a
    // console.info as evidence (see init()).
    var grid = el("div", "grid");
    var anyButtons = false;
    unsortedCaptions.forEach(function (caption) {
      var w = byCaption.get(caption);
      if (!w || w.kind !== "button") return;
      grid.appendChild(renderTile(w));
      anyButtons = true;
    });
    if (anyButtons) card.appendChild(grid);
    unsortedCaptions.forEach(function (caption) {
      var w = byCaption.get(caption);
      if (!w) return;
      if (w.kind === "slider") card.appendChild(renderSlider(w));
      else if (w.kind === "cuelist") card.appendChild(renderCueListWidget(w));
      else if (w.kind === "speeddial") card.appendChild(renderTempoWidget(w));
    });
    return card;
  }

  function renderAutoParkToggle() {
    var card = el("div", "section");
    card.appendChild(el("div", "section-title", "Automation"));
    var row = el("div", "toggle-row");
    row.appendChild(el("span", null, "Auto-park MH Dim for dim-only routines"));
    var sw = el("span", "switch" + (autoParkEnabled ? " on" : ""));
    row.appendChild(sw);
    row.addEventListener("click", function () {
      autoParkEnabled = !autoParkEnabled;
      localStorage.setItem("despacio.autoParkEnabled", autoParkEnabled ? "1" : "0");
      sw.classList.toggle("on", autoParkEnabled);
      // Turning auto-park off mid-park used to just hide the badge and leave
      // MH Dim sitting at the park target with no way back except a manual
      // fader move -- restore it for real instead.
      if (!autoParkEnabled) restoreParkNow();
    });
    card.appendChild(row);
    return card;
  }

  // gen_webui_config.py stamps _generated on every write, but nothing ever
  // surfaced it -- if the generator errors out (a lint failure) serve.py
  // only warns on ITS OWN stdout and quietly serves the last-good
  // ui_config.js, with no way to notice from the phone that it's stale.
  function renderGeneratedFooter() {
    var gen = VC._generated;
    var text = "Config not generated (no _generated block in ui_config.js)";
    if (gen && gen.generatedAt) {
      var when;
      try { when = new Date(gen.generatedAt).toLocaleString(); }
      catch (e) { when = gen.generatedAt; }
      text = "Config generated " + when;
    }
    return el("div", "setup-note generated-footer", text);
  }

  // -------------------------------------------------------------- header

  function renderHeader() {
    var wrap = document.getElementById("headerWidgets");
    wrap.innerHTML = "";
    (LAYOUT.header.items || []).forEach(function (caption) {
      var w = byCaption.get(caption);
      if (!w) return;
      if (w.kind === "slider") {
        var s = renderSlider(w, { shortLabel: caption });
        s.classList.add("header-slider");
        wrap.appendChild(s);
      } else if (w.kind === "button") {
        var extra = caption === "Blackout" ? "blackout-btn" : null;
        wrap.appendChild(renderTile(w, extra));
      }
    });
  }

  // --------------------------------------------------------------- tabs

  var activeTabId = LAYOUT.tabs[0].id;

  function renderTabBar() {
    var bar = document.getElementById("tabbar");
    bar.innerHTML = "";
    LAYOUT.tabs.forEach(function (tab) {
      var b = el("button", "tab" + (tab.id === activeTabId ? " active" : ""));
      b.appendChild(el("span", "icon", tab.icon || "•"));
      b.appendChild(el("span", null, tab.label));
      b.addEventListener("click", function () { selectTab(tab.id); });
      bar.appendChild(b);
    });
  }

  function selectTab(id) {
    activeTabId = id;
    renderTabBar();
    var tab = LAYOUT.tabs.filter(function (t) { return t.id === id; })[0];
    renderTab(tab);
    window.scrollTo(0, 0); // otherwise a long tab's scroll position leaks into a short one
  }

  // --------------------------------------------------- MH Dim auto-park

  // Every caption gen_webui_config.py flagged as an HTP conflict against a
  // slider, keyed by that slider's caption -- built from VC.dimConflicts so
  // this stays correct even before ui_layout.js's dimPark/dimParkExempt are
  // consulted (those only decide the TARGET, not which routines matter).
  var dimConflictsBySlider = {};
  VC.dimConflicts.forEach(function (c) {
    (dimConflictsBySlider[c.sliderCaption] = dimConflictsBySlider[c.sliderCaption] || [])
      .push(c.buttonCaption);
  });

  // Every widget caption aim_calc.py's POSE REACHABILITY report flagged as
  // clamped/rounded away from its geometric target -- built from
  // VC.aimWarnings (gen_webui_config.py's resolve_aim_warnings(), which
  // already resolved aim_report.json's function IDs down to widget
  // captions). See renderTile() below for where this gets a tile marker,
  // and showAimBadge()/aimBadge (index.html) for the tap-to-detail surface.
  var aimWarningsByCaption = {};
  (VC.aimWarnings || []).forEach(function (w) {
    aimWarningsByCaption[w.caption] = w;
  });

  var mhDimWidget = byCaption.get("MH Dim");
  var mhDimOwningCaptions = dimConflictsBySlider["MH Dim"] || [];
  var mhDimActiveOwners = new Set();
  var mhDimParkState = null; // {savedValue, parkedBy: [captions]} | null
  var autoParkEnabled = localStorage.getItem("despacio.autoParkEnabled") !== "0";
  var mhDimManualOverride = false;

  function loadParkState() {
    try {
      var raw = sessionStorage.getItem("despacio.mhDimPark");
      return raw ? JSON.parse(raw) : null;
    } catch (e) { return null; }
  }
  function saveParkState() {
    if (mhDimParkState) sessionStorage.setItem("despacio.mhDimPark", JSON.stringify(mhDimParkState));
    else sessionStorage.removeItem("despacio.mhDimPark");
  }
  mhDimParkState = loadParkState();

  function parkTargetFor(captions) {
    var targets = captions
      .map(function (c) { return LAYOUT.dimPark[c]; })
      .filter(function (v) { return typeof v === "number"; });
    return targets.length ? Math.min.apply(null, targets) : 0;
  }

  function onButtonActiveChanged(widget, active) {
    if (!mhDimWidget || mhDimOwningCaptions.indexOf(widget.caption) === -1) {
      if (!seeding) updateBanners();
      return;
    }
    if (active) mhDimActiveOwners.add(widget.caption);
    else mhDimActiveOwners.delete(widget.caption);
    // While the seed burst is landing (see `seeding` above), just track
    // ownership -- don't park/restore or repaint banners per-widget off a
    // partial picture. finishSeeding() reconciles both, once, after the
    // burst settles.
    if (seeding) return;
    updateMhDimPark();
    updateBanners();
  }

  function updateMhDimPark() {
    if (!autoParkEnabled || !mhDimWidget) return;
    if (mhDimActiveOwners.size > 0) {
      if (!mhDimParkState) {
        mhDimParkState = {
          savedValue: state.has(mhDimWidget.id) ? state.get(mhDimWidget.id) : mhDimWidget.value,
          parkedBy: [],
        };
        mhDimManualOverride = false;
      }
      mhDimParkState.parkedBy = Array.from(mhDimActiveOwners);
      var target = parkTargetFor(mhDimParkState.parkedBy);
      if (!mhDimManualOverride) sendSliderValue(mhDimWidget, target);
      saveParkState();
      renderParkBadge();
    } else if (mhDimParkState) {
      if (!mhDimManualOverride) sendSliderValue(mhDimWidget, mhDimParkState.savedValue);
      mhDimParkState = null;
      mhDimManualOverride = false;
      saveParkState();
      clearParkBadge();
    }
  }

  function onMhDimManualMove() {
    if (mhDimParkState) {
      mhDimManualOverride = true;
      renderParkBadge();
    }
    updateBanners();
  }

  function onMhDimExternalChange(_val) {
    // The slider moved via the APC40 or another client -- if we're mid-park
    // and it wasn't us (sliderLocalUntil already filters our own echoes),
    // treat it the same as a manual override so we don't fight it back.
    if (mhDimParkState) {
      mhDimManualOverride = true;
      renderParkBadge();
    }
    updateBanners();
  }

  function restoreParkNow() {
    if (!mhDimParkState || !mhDimWidget) return;
    mhDimManualOverride = false;
    sendSliderValue(mhDimWidget, mhDimParkState.savedValue);
    mhDimParkState = null;
    saveParkState();
    clearParkBadge();
  }

  function renderParkBadge() {
    var badge = document.getElementById("parkBadge");
    if (!mhDimParkState) { badge.hidden = true; return; }
    badge.hidden = false;
    badge.innerHTML = "";
    var label = mhDimManualOverride
      ? "MH Dim: manual override (" + mhDimParkState.parkedBy.join(", ") + " still running)"
      : "MH Dim parked by " + mhDimParkState.parkedBy.join(", ") +
        " · restores to " + Math.round((mhDimParkState.savedValue / (mhDimWidget.high - mhDimWidget.low)) * 100) + "%";
    badge.appendChild(el("span", null, label));
    var btn = el("button", null, "Restore now");
    btn.addEventListener("click", restoreParkNow);
    badge.appendChild(btn);
  }
  function clearParkBadge() {
    var badge = document.getElementById("parkBadge");
    badge.hidden = true;
  }

  // ------------------------------------------------ aim reachability badge

  // Tap-to-detail for the [data-aim-warn] tile marker set in renderTile()
  // above. Deliberately its OWN badge element (index.html's #aimBadge), not
  // a reuse of #parkBadge -- MH Dim parking and pose reachability are
  // unrelated conditions that can both be live at once (e.g. Teleport is
  // both an MH-Dim-owning routine AND a flagged pose), and sharing one
  // element would let whichever updated last silently clobber the other.
  function showAimBadge(warn) {
    var badge = document.getElementById("aimBadge");
    badge.hidden = false;
    badge.classList.toggle("severity-significant", warn.severity === "significant");
    badge.innerHTML = "";
    var note = warn.severity === "minor"
      ? "expected clamp, not a calibration problem"
      : "check calibration before relying on this";
    var label = el("span", null,
      warn.caption + ": " + warn.poses.join(", ") + " -- up to " + warn.maxErrorDeg +
      "° off target (" + note + ")");
    badge.appendChild(label);
    var btn = el("button", null, "Dismiss");
    btn.addEventListener("click", clearAimBadge);
    badge.appendChild(btn);
  }
  function clearAimBadge() {
    var badge = document.getElementById("aimBadge");
    badge.hidden = true;
  }

  // On load, if a park was left active from a previous session but nothing
  // is actually running anymore, restore rather than strand the rig low.
  function reconcileParkOnLoad() {
    if (!mhDimParkState) return;
    // We don't know yet whether the owning routines are still running --
    // wait for the initial getWidgetStatus burst (onOpen) to populate
    // mhDimActiveOwners via applyStatus -> onButtonActiveChanged (deferred
    // while `seeding` is true), then finishSeeding() calls updateMhDimPark()
    // once to reconcile for real. Just render the badge now so it's not
    // silently invisible in the meantime.
    renderParkBadge();
  }

  // ---------------------------------------------------- layer-with-no-pose

  // Any button whose function is Drift/Counter-Orbit-style "layer" -- see
  // despacio/README.md, "Drift / Counter-Orbit are LAYERS, not looks".
  // Hand-kept in ui_layout.js (not structurally derivable -- EFX functions
  // write no Scene FixtureVal at all) but linted there against real widget
  // captions by gen_webui_config.py.
  var LAYER_CAPTIONS = LAYOUT.layerCaptions || [];
  // Position/movement family -- any of these being active counts as "a pose
  // is under the layer". Structurally derived by gen_webui_config.py's
  // resolve_movement_and_color() from which functions actually write a
  // Position-group channel (Pan/Tilt) -- see that function's docstring. This
  // used to be a hand-kept caption list here that nothing validated against
  // the live workspace (and had gone stale: it excluded "Build" on the
  // theory that it "writes no pan/tilt at all", which despacio.qxw's Build
  // Chaser's steps -- Walls -> Iris Out -> Ball -> Apex -> Zenith -- disprove).
  var POSE_CAPTIONS = VC.poseCaptions || [];
  // Colour family -- any of these being active means the shutter/gobo chain
  // is plausibly already open (see README: base colour scenes bake
  // Strobe=0). Used only for the soft Beam Open hint below, not a hard rule.
  // Structurally derived the same way as POSE_CAPTIONS, from Colour-group
  // channel writes (this show's moving heads expose colour as a single
  // Colour-Wheel-preset channel, not RGB intensities).
  var COLOR_CAPTIONS = VC.colorCaptions || [];

  // A cuelist counts as active when its chaser is running -- checked via
  // runningFunctions (the signal every FUNCTION broadcast updates, live or
  // seeded) with a state.playing fallback for the brief window right after a
  // reload before the first broadcast lands. Previously isActive() only
  // handled the button shape (state.get(id) === 255), so a pose or colour
  // look driven by the Night CueList's chaser -- now in POSE_CAPTIONS/
  // COLOR_CAPTIONS above, since resolve_movement_and_color() resolves
  // CueList widgets too -- could never actually satisfy either banner check.
  function isActive(caption) {
    var w = byCaption.get(caption);
    if (!w) return false;
    if (w.kind === "cuelist") {
      if (w.chaserId != null && runningFunctions.has(w.chaserId)) return true;
      var st = state.get(w.id);
      return !!(st && st.playing);
    }
    return state.get(w.id) === 255;
  }

  function updateBanners() {
    var banner = document.getElementById("banner");

    // Highest priority of all: previously a disconnected socket was only
    // visible as a 10px dot in the header (setConnState()'s `title` attribute
    // never surfaces on a touchscreen), so every press silently did nothing
    // with no on-screen explanation. Every other banner below describes rig
    // STATE we can't actually vouch for right now, so skip straight past them.
    if (connState !== "connected") {
      banner.hidden = false;
      banner.className = "banner disconnected";
      banner.innerHTML = "";
      banner.appendChild(el("span", null, connState === "connecting"
        ? "Connecting to QLC+…"
        : "Not connected to QLC+ -- controls won't do anything until this reconnects."));
      return;
    }

    // Highest priority otherwise: a dark rig with no obvious on-screen cause is the
    // worst thing to debug mid-show, and .w-tile.active/.blackout-btn.active
    // render the same accent blue (see styles.css), so the tile alone
    // doesn't say enough. Checked first and unconditionally -- overrides the
    // other banners below since nothing is visible while this is true.
    if (isActive("Blackout")) {
      banner.hidden = false;
      banner.className = "banner blackout";
      banner.innerHTML = "";
      banner.appendChild(el("span", null,
        "BLACKOUT is active -- all output is dark regardless of any look or fader."));
      var off = el("button", null, "Blackout off");
      off.addEventListener("click", function () {
        var w = byCaption.get("Blackout");
        if (w) pressToggle(w);
      });
      banner.appendChild(off);
      return;
    }

    var layerActive = LAYER_CAPTIONS.some(isActive);
    var poseActive = POSE_CAPTIONS.some(isActive);

    if (layerActive && !poseActive) {
      banner.hidden = false;
      banner.className = "banner";
      banner.innerHTML = "";
      banner.appendChild(el("span", null,
        "A layer (Drift/Counter-Orbit) is running with no pose under it -- it will integrate " +
        "and the beams will slam to a rail. "));
      var fix = el("button", null, "To Ball");
      fix.addEventListener("click", function () {
        var w = byCaption.get("To Ball");
        if (w) send(w.id + "|1");
      });
      banner.appendChild(fix);
      return;
    }

    var mhDimUp = mhDimWidget && (state.has(mhDimWidget.id) ? state.get(mhDimWidget.id) : mhDimWidget.value) > 0;
    var beamOpen = isActive("Beam Open");
    var colorActive = COLOR_CAPTIONS.some(isActive);
    if (mhDimUp && !beamOpen && !colorActive) {
      banner.hidden = false;
      banner.className = "banner warn";
      banner.innerHTML = "";
      banner.appendChild(el("span", null,
        "MH Dim is up but Beam Open hasn't been pressed and no colour look is active -- " +
        "the heads may not be visibly lit yet. "));
      var open = el("button", null, "Beam Open");
      open.addEventListener("click", function () {
        var w = byCaption.get("Beam Open");
        if (w) send(w.id + "|1");
      });
      banner.appendChild(open);
      return;
    }

    banner.hidden = true;
  }

  // ------------------------------------------------------------ wake lock

  function requestWakeLock() {
    if (!("wakeLock" in navigator)) return;
    navigator.wakeLock.request("screen").catch(function () {});
  }
  document.addEventListener("visibilitychange", function () {
    if (document.visibilityState === "visible") requestWakeLock();
    else releaseAllHeldFlash();
  });
  window.addEventListener("blur", releaseAllHeldFlash);

  // ------------------------------------------------------------------ init

  function init() {
    renderHeader();
    renderTabBar();
    selectTab(activeTabId);
    reconcileParkOnLoad();
    requestWakeLock();
    connect();
    if (unsortedCaptions.length) {
      console.info("despacio webui: " + unsortedCaptions.length + " widget(s) not placed in " +
        "ui_layout.js, rendered under Show > Unsorted:", unsortedCaptions);
    }
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);
  else init();
})();
