// GENERATED by gen_webui_config.py -- do not hand-edit, it will be overwritten.
window.VC = {
  "_generated": {
    "generatedAt": "2026-08-01T06:01:24+00:00",
    "qxwSha256": "29c5259b80f983d13f5b06de56d2477127b8883da1a563a45c0c9fb610746c3d",
    "qxwPath": "despacio.qxw"
  },
  "widgets": [
    {
      "kind": "slider",
      "id": 150,
      "caption": "Pan MH1",
      "mode": "Level",
      "displayStyle": "Exact",
      "low": 0,
      "high": 255,
      "value": 128,
      "channels": [
        [
          0,
          0
        ]
      ],
      "adjustFunctionId": null
    },
    {
      "kind": "button",
      "id": 100,
      "caption": "White",
      "functionId": 0,
      "functionName": "MH White",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 101,
      "caption": "Red",
      "functionId": 1,
      "functionName": "MH Red",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 102,
      "caption": "Blue",
      "functionId": 2,
      "functionName": "MH Blue",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 103,
      "caption": "Pink",
      "functionId": 3,
      "functionName": "MH Pink",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 104,
      "caption": "Orange",
      "functionId": 4,
      "functionName": "MH Orange",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 105,
      "caption": "Color Auto",
      "functionId": 5,
      "functionName": "MH Color Auto",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 106,
      "caption": "Sunset",
      "functionId": 26,
      "functionName": "MH Sunset",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "slider",
      "id": 151,
      "caption": "MH Dim",
      "mode": "Level",
      "displayStyle": "Exact",
      "low": 0,
      "high": 255,
      "value": 70,
      "channels": [
        [
          0,
          7
        ],
        [
          1,
          7
        ],
        [
          2,
          7
        ],
        [
          3,
          7
        ]
      ],
      "adjustFunctionId": null
    },
    {
      "kind": "slider",
      "id": 152,
      "caption": "Pan MH2",
      "mode": "Level",
      "displayStyle": "Exact",
      "low": 0,
      "high": 255,
      "value": 128,
      "channels": [
        [
          1,
          0
        ]
      ],
      "adjustFunctionId": null
    },
    {
      "kind": "button",
      "id": 107,
      "caption": "To Ball",
      "functionId": 6,
      "functionName": "Heads - Ball",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 108,
      "caption": "To Floor",
      "functionId": 7,
      "functionName": "Heads - Floor",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 109,
      "caption": "To Walls",
      "functionId": 8,
      "functionName": "Heads - Walls",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 110,
      "caption": "Lazy Circle",
      "functionId": 18,
      "functionName": "Lazy Circle",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 111,
      "caption": "To Crowd",
      "functionId": 51,
      "functionName": "Heads - Crowd",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 112,
      "caption": "Cross Weave",
      "functionId": 35,
      "functionName": "Cross Weave",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 1009,
      "caption": "Wall Graze",
      "functionId": 199,
      "functionName": "Heads - Wall Graze",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 113,
      "caption": "Beam Open",
      "functionId": 9,
      "functionName": "MH Beam Open",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "slider",
      "id": 153,
      "caption": "PT Speed",
      "mode": "Level",
      "displayStyle": "Exact",
      "low": 0,
      "high": 255,
      "value": 0,
      "channels": [
        [
          0,
          8
        ],
        [
          1,
          8
        ],
        [
          2,
          8
        ],
        [
          3,
          8
        ]
      ],
      "adjustFunctionId": null
    },
    {
      "kind": "slider",
      "id": 154,
      "caption": "Pan MH3",
      "mode": "Level",
      "displayStyle": "Exact",
      "low": 0,
      "high": 255,
      "value": 128,
      "channels": [
        [
          2,
          0
        ]
      ],
      "adjustFunctionId": null
    },
    {
      "kind": "button",
      "id": 114,
      "caption": "Color Drift",
      "functionId": 21,
      "functionName": "Color Drift",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 115,
      "caption": "Color Spin",
      "functionId": 27,
      "functionName": "MH Color Spin",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 122,
      "caption": "Rainbow Wheel",
      "functionId": 61,
      "functionName": "Rainbow Wheel",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "slider",
      "id": 155,
      "caption": "Color Scroll",
      "mode": "Level",
      "displayStyle": "Exact",
      "low": 0,
      "high": 255,
      "value": 0,
      "channels": [
        [
          0,
          4
        ],
        [
          1,
          4
        ],
        [
          2,
          4
        ],
        [
          3,
          4
        ]
      ],
      "adjustFunctionId": null
    },
    {
      "kind": "button",
      "id": 116,
      "caption": "Slow Pulse",
      "functionId": 28,
      "functionName": "MH Slow Pulse",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 917,
      "caption": "Medium Pulse",
      "functionId": 130,
      "functionName": "MH Medium Pulse",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "slider",
      "id": 156,
      "caption": "Pan MH4",
      "mode": "Level",
      "displayStyle": "Exact",
      "low": 0,
      "high": 255,
      "value": 128,
      "channels": [
        [
          3,
          0
        ]
      ],
      "adjustFunctionId": null
    },
    {
      "kind": "button",
      "id": 117,
      "caption": "Diagonal Pulse",
      "functionId": 44,
      "functionName": "Diagonal Pulse",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 118,
      "caption": "Corner Chase",
      "functionId": 49,
      "functionName": "Corner Chase",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 119,
      "caption": "Grand Sweep",
      "functionId": 50,
      "functionName": "Grand Sweep",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 120,
      "caption": "Slow Sweep",
      "functionId": 19,
      "functionName": "Slow Sweep",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 121,
      "caption": "Ball Spiral",
      "functionId": 60,
      "functionName": "Ball Spiral",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 902,
      "caption": "Floor Ring",
      "functionId": 121,
      "functionName": "Floor Ring",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 903,
      "caption": "Floor Wipe",
      "functionId": 126,
      "functionName": "Floor Wipe",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 904,
      "caption": "Floor Cross",
      "functionId": 129,
      "functionName": "Floor Cross",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 997,
      "caption": "Floor Bounce",
      "functionId": 173,
      "functionName": "Floor Bounce",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 998,
      "caption": "Floor Breathe",
      "functionId": 176,
      "functionName": "Floor Breathe",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "slider",
      "id": 158,
      "caption": "Tilt MH1",
      "mode": "Level",
      "displayStyle": "Exact",
      "low": 0,
      "high": 255,
      "value": 128,
      "channels": [
        [
          0,
          2
        ]
      ],
      "adjustFunctionId": null
    },
    {
      "kind": "button",
      "id": 123,
      "caption": "Warm Up",
      "functionId": 39,
      "functionName": "Warm Up",
      "functionType": "Collection",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 124,
      "caption": "Idle",
      "functionId": 22,
      "functionName": "Despacio Idle",
      "functionType": "Collection",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 125,
      "caption": "Deep",
      "functionId": 40,
      "functionName": "Deep",
      "functionType": "Collection",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 126,
      "caption": "Peak",
      "functionId": 23,
      "functionName": "Peak",
      "functionType": "Collection",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 127,
      "caption": "Landing",
      "functionId": 41,
      "functionName": "Landing",
      "functionType": "Collection",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 700,
      "caption": "Spiral",
      "functionId": 62,
      "functionName": "Spiral",
      "functionType": "Collection",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "slider",
      "id": 159,
      "caption": "Tilt MH2",
      "mode": "Level",
      "displayStyle": "Exact",
      "low": 0,
      "high": 255,
      "value": 128,
      "channels": [
        [
          1,
          2
        ]
      ],
      "adjustFunctionId": null
    },
    {
      "kind": "button",
      "id": 128,
      "caption": "Test Corner 1",
      "functionId": 45,
      "functionName": "Chase Pos 1",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 129,
      "caption": "Test Corner 2",
      "functionId": 46,
      "functionName": "Chase Pos 2",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 130,
      "caption": "Test Corner 3",
      "functionId": 47,
      "functionName": "Chase Pos 3",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 131,
      "caption": "Test Corner 4",
      "functionId": 48,
      "functionName": "Chase Pos 4",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 996,
      "caption": "Reset Heads",
      "functionId": 178,
      "functionName": "Reset Heads",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": false
    },
    {
      "kind": "slider",
      "id": 161,
      "caption": "Tilt MH3",
      "mode": "Level",
      "displayStyle": "Exact",
      "low": 0,
      "high": 255,
      "value": 128,
      "channels": [
        [
          2,
          2
        ]
      ],
      "adjustFunctionId": null
    },
    {
      "kind": "button",
      "id": 132,
      "caption": "White Bump",
      "functionId": 33,
      "functionName": "White Bump",
      "functionType": "Scene",
      "action": "Flash",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 134,
      "caption": "Strobe",
      "functionId": 10,
      "functionName": "MH Strobe",
      "functionType": "Scene",
      "action": "Flash",
      "hasInput": true
    },
    {
      "kind": "slider",
      "id": 172,
      "caption": "MH Strobe",
      "mode": "Level",
      "displayStyle": "Exact",
      "low": 0,
      "high": 255,
      "value": 0,
      "channels": [
        [
          0,
          6
        ],
        [
          1,
          6
        ],
        [
          2,
          6
        ],
        [
          3,
          6
        ]
      ],
      "adjustFunctionId": null
    },
    {
      "kind": "slider",
      "id": 162,
      "caption": "Tilt MH4",
      "mode": "Level",
      "displayStyle": "Exact",
      "low": 0,
      "high": 255,
      "value": 128,
      "channels": [
        [
          3,
          2
        ]
      ],
      "adjustFunctionId": null
    },
    {
      "kind": "button",
      "id": 138,
      "caption": "Ball Wave",
      "functionId": 67,
      "functionName": "Ball Wave",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 139,
      "caption": "Circle",
      "functionId": 78,
      "functionName": "Heads - Circle",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 140,
      "caption": "Neighbor Scan",
      "functionId": 81,
      "functionName": "Neighbor Scan",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 141,
      "caption": "Prowl",
      "functionId": 86,
      "functionName": "Prowl",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 142,
      "caption": "Crowd Cascade",
      "functionId": 91,
      "functionName": "Crowd Cascade",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 136,
      "caption": "Dim Chase",
      "functionId": 72,
      "functionName": "Dim Chase",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 137,
      "caption": "Spotlight",
      "functionId": 77,
      "functionName": "Spotlight",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 1011,
      "caption": "MH Breathe",
      "functionId": 220,
      "functionName": "MH Breathe",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "slider",
      "id": 163,
      "caption": "MH Gobo",
      "mode": "Level",
      "displayStyle": "Exact",
      "low": 0,
      "high": 255,
      "value": 0,
      "channels": [
        [
          0,
          5
        ],
        [
          1,
          5
        ],
        [
          2,
          5
        ],
        [
          3,
          5
        ]
      ],
      "adjustFunctionId": null
    },
    {
      "kind": "slider",
      "id": 164,
      "caption": "Master Dimmer",
      "mode": "Submaster",
      "displayStyle": "Percentage",
      "low": 0,
      "high": 255,
      "value": 255,
      "channels": [],
      "adjustFunctionId": null
    },
    {
      "kind": "button",
      "id": 135,
      "caption": "Blackout",
      "functionId": null,
      "functionName": null,
      "functionType": null,
      "action": "Blackout",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 701,
      "caption": "Apex",
      "functionId": 92,
      "functionName": "Heads - Apex",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 702,
      "caption": "Cathedral",
      "functionId": 93,
      "functionName": "Heads - Cathedral",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 703,
      "caption": "Zenith",
      "functionId": 94,
      "functionName": "Heads - Zenith",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 704,
      "caption": "Rise",
      "functionId": 95,
      "functionName": "Rise",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 705,
      "caption": "Iris",
      "functionId": 98,
      "functionName": "Iris",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 1010,
      "caption": "Canopy Ring",
      "functionId": 204,
      "functionName": "Canopy Ring",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 728,
      "caption": "Split Warm/Cool",
      "functionId": 103,
      "functionName": "Split Warm/Cool",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 729,
      "caption": "Split Red/Cyan",
      "functionId": 104,
      "functionName": "Split Red/Cyan",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 730,
      "caption": "Split Pink/Green",
      "functionId": 105,
      "functionName": "Split Pink/Green",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 731,
      "caption": "Duo Cyan/Pink",
      "functionId": 106,
      "functionName": "Duo Cyan/Pink",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 732,
      "caption": "Duo Green/Blue",
      "functionId": 107,
      "functionName": "Duo Green/Blue",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 984,
      "caption": "Split Yellow/Blue",
      "functionId": 167,
      "functionName": "Split Yellow/Blue",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 985,
      "caption": "Split White/Orange",
      "functionId": 168,
      "functionName": "Split White/Orange",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 986,
      "caption": "Split Red/Green",
      "functionId": 169,
      "functionName": "Split Red/Green",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 749,
      "caption": "Drift",
      "functionId": 99,
      "functionName": "Drift",
      "functionType": "EFX",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 750,
      "caption": "Counter-Orbit",
      "functionId": 100,
      "functionName": "Counter-Orbit",
      "functionType": "EFX",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 1076,
      "caption": "Shiver",
      "functionId": 223,
      "functionName": "Shiver",
      "functionType": "EFX",
      "action": "Toggle",
      "hasInput": false
    },
    {
      "kind": "button",
      "id": 1077,
      "caption": "Figure Eight",
      "functionId": 224,
      "functionName": "Figure Eight",
      "functionType": "EFX",
      "action": "Toggle",
      "hasInput": false
    },
    {
      "kind": "button",
      "id": 1078,
      "caption": "Diamond Weave",
      "functionId": 225,
      "functionName": "Diamond Weave",
      "functionType": "EFX",
      "action": "Toggle",
      "hasInput": false
    },
    {
      "kind": "button",
      "id": 751,
      "caption": "Build",
      "functionId": 101,
      "functionName": "Build",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 752,
      "caption": "Drop",
      "functionId": 102,
      "functionName": "Drop",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "slider",
      "id": 170,
      "caption": "Drift Width",
      "mode": "Adjust",
      "displayStyle": "Exact",
      "low": 0,
      "high": 255,
      "value": 128,
      "channels": [],
      "adjustFunctionId": 99
    },
    {
      "kind": "button",
      "id": 753,
      "caption": "Pin Glow",
      "functionId": 108,
      "functionName": "Pin Ball Glow",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 754,
      "caption": "Pin Drift",
      "functionId": 115,
      "functionName": "Pin Drift",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 918,
      "caption": "Pin Amber",
      "functionId": 109,
      "functionName": "Pin Amber",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 919,
      "caption": "Pin Rose",
      "functionId": 110,
      "functionName": "Pin Rose",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 920,
      "caption": "Pin Magenta",
      "functionId": 111,
      "functionName": "Pin Magenta",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 921,
      "caption": "Pin Indigo",
      "functionId": 112,
      "functionName": "Pin Indigo",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 922,
      "caption": "Pin Teal",
      "functionId": 113,
      "functionName": "Pin Teal",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 923,
      "caption": "Pin Sea",
      "functionId": 114,
      "functionName": "Pin Sea",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 924,
      "caption": "Pin Rainbow",
      "functionId": 143,
      "functionName": "Pin Rainbow",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 1012,
      "caption": "Pin Split",
      "functionId": 221,
      "functionName": "Pin Split",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "slider",
      "id": 171,
      "caption": "Pin Dim",
      "mode": "Level",
      "displayStyle": "Exact",
      "low": 9,
      "high": 134,
      "value": 134,
      "channels": [
        [
          4,
          0
        ],
        [
          5,
          0
        ]
      ],
      "adjustFunctionId": null
    },
    {
      "kind": "button",
      "id": 925,
      "caption": "Pin Breathe",
      "functionId": 146,
      "functionName": "Pin Breathe",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 1014,
      "caption": "Pin Strobe",
      "functionId": 222,
      "functionName": "Pin Strobe",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 950,
      "caption": "Teleport",
      "functionId": 155,
      "functionName": "Teleport",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 951,
      "caption": "Apparition",
      "functionId": 156,
      "functionName": "Apparition",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 952,
      "caption": "Freeze Frame",
      "functionId": 161,
      "functionName": "Freeze Frame",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 953,
      "caption": "Stutter",
      "functionId": 166,
      "functionName": "Stutter",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 1079,
      "caption": "Glitch",
      "functionId": 226,
      "functionName": "Glitch",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": false
    },
    {
      "kind": "button",
      "id": 1080,
      "caption": "Ascension",
      "functionId": 235,
      "functionName": "Ascension",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": false
    },
    {
      "kind": "button",
      "id": 1081,
      "caption": "Blink",
      "functionId": 244,
      "functionName": "Blink",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": false
    },
    {
      "kind": "button",
      "id": 1015,
      "caption": "Yellow",
      "functionId": 205,
      "functionName": "MH Yellow",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 1016,
      "caption": "Green",
      "functionId": 206,
      "functionName": "MH Green",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 1017,
      "caption": "Cyan",
      "functionId": 207,
      "functionName": "MH Cyan",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 1018,
      "caption": "Quad Spectrum",
      "functionId": 208,
      "functionName": "Quad Spectrum",
      "functionType": "Scene",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "button",
      "id": 1019,
      "caption": "Wheel Walk",
      "functionId": 217,
      "functionName": "Wheel Walk",
      "functionType": "Chaser",
      "action": "Toggle",
      "hasInput": true
    },
    {
      "kind": "cuelist",
      "id": 901,
      "caption": "Night",
      "chaserId": 116,
      "chaserName": "Night",
      "slidersMode": "Crossfade",
      "steps": [
        {
          "functionId": 39,
          "name": "Warm Up",
          "holdMs": 180000
        },
        {
          "functionId": 22,
          "name": "Despacio Idle",
          "holdMs": 240000
        },
        {
          "functionId": 40,
          "name": "Deep",
          "holdMs": 240000
        },
        {
          "functionId": 62,
          "name": "Spiral",
          "holdMs": 180000
        },
        {
          "functionId": 93,
          "name": "Heads - Cathedral",
          "holdMs": 120000
        },
        {
          "functionId": 23,
          "name": "Peak",
          "holdMs": 240000
        },
        {
          "functionId": 101,
          "name": "Build",
          "holdMs": 20000
        },
        {
          "functionId": 102,
          "name": "Drop",
          "holdMs": 30000
        },
        {
          "functionId": 41,
          "name": "Landing",
          "holdMs": null
        }
      ]
    },
    {
      "kind": "speeddial",
      "id": 900,
      "caption": "Tempo (tap 1 per bar)",
      "timeMs": 2000,
      "minMs": 500,
      "maxMs": 8000,
      "attachedFunctionIds": [
        18,
        19,
        21,
        35,
        44,
        49,
        50,
        60,
        61,
        217,
        220,
        67,
        72,
        77,
        81,
        86,
        91,
        95,
        98,
        99,
        100,
        223,
        224,
        225,
        115,
        121,
        204,
        126,
        129,
        173,
        176,
        143,
        146,
        161
      ]
    }
  ],
  "dimConflicts": [
    {
      "buttonId": 141,
      "buttonCaption": "Prowl",
      "sliderId": 151,
      "sliderCaption": "MH Dim",
      "fixturesWritten": [
        0,
        1,
        2,
        3
      ],
      "fixturesInSlider": [
        0,
        1,
        2,
        3
      ]
    },
    {
      "buttonId": 142,
      "buttonCaption": "Crowd Cascade",
      "sliderId": 151,
      "sliderCaption": "MH Dim",
      "fixturesWritten": [
        0,
        1,
        2,
        3
      ],
      "fixturesInSlider": [
        0,
        1,
        2,
        3
      ]
    },
    {
      "buttonId": 136,
      "buttonCaption": "Dim Chase",
      "sliderId": 151,
      "sliderCaption": "MH Dim",
      "fixturesWritten": [
        0,
        1,
        2,
        3
      ],
      "fixturesInSlider": [
        0,
        1,
        2,
        3
      ]
    },
    {
      "buttonId": 137,
      "buttonCaption": "Spotlight",
      "sliderId": 151,
      "sliderCaption": "MH Dim",
      "fixturesWritten": [
        0,
        1,
        2,
        3
      ],
      "fixturesInSlider": [
        0,
        1,
        2,
        3
      ]
    },
    {
      "buttonId": 1011,
      "buttonCaption": "MH Breathe",
      "sliderId": 151,
      "sliderCaption": "MH Dim",
      "fixturesWritten": [
        0,
        1,
        2,
        3
      ],
      "fixturesInSlider": [
        0,
        1,
        2,
        3
      ]
    },
    {
      "buttonId": 752,
      "buttonCaption": "Drop",
      "sliderId": 151,
      "sliderCaption": "MH Dim",
      "fixturesWritten": [
        0,
        1,
        2,
        3
      ],
      "fixturesInSlider": [
        0,
        1,
        2,
        3
      ]
    },
    {
      "buttonId": 950,
      "buttonCaption": "Teleport",
      "sliderId": 151,
      "sliderCaption": "MH Dim",
      "fixturesWritten": [
        0,
        1,
        2,
        3
      ],
      "fixturesInSlider": [
        0,
        1,
        2,
        3
      ]
    },
    {
      "buttonId": 951,
      "buttonCaption": "Apparition",
      "sliderId": 151,
      "sliderCaption": "MH Dim",
      "fixturesWritten": [
        0,
        1,
        2,
        3
      ],
      "fixturesInSlider": [
        0,
        1,
        2,
        3
      ]
    },
    {
      "buttonId": 952,
      "buttonCaption": "Freeze Frame",
      "sliderId": 151,
      "sliderCaption": "MH Dim",
      "fixturesWritten": [
        0,
        1,
        2,
        3
      ],
      "fixturesInSlider": [
        0,
        1,
        2,
        3
      ]
    },
    {
      "buttonId": 953,
      "buttonCaption": "Stutter",
      "sliderId": 151,
      "sliderCaption": "MH Dim",
      "fixturesWritten": [
        0,
        1,
        2,
        3
      ],
      "fixturesInSlider": [
        0,
        1,
        2,
        3
      ]
    },
    {
      "buttonId": 1079,
      "buttonCaption": "Glitch",
      "sliderId": 151,
      "sliderCaption": "MH Dim",
      "fixturesWritten": [
        0,
        1,
        2,
        3
      ],
      "fixturesInSlider": [
        0,
        1,
        2,
        3
      ]
    },
    {
      "buttonId": 1080,
      "buttonCaption": "Ascension",
      "sliderId": 151,
      "sliderCaption": "MH Dim",
      "fixturesWritten": [
        0,
        1,
        2,
        3
      ],
      "fixturesInSlider": [
        0,
        1,
        2,
        3
      ]
    },
    {
      "buttonId": 1081,
      "buttonCaption": "Blink",
      "sliderId": 151,
      "sliderCaption": "MH Dim",
      "fixturesWritten": [
        0,
        1,
        2,
        3
      ],
      "fixturesInSlider": [
        0,
        1,
        2,
        3
      ]
    }
  ],
  "aimWarnings": [
    {
      "caption": "Ball Spiral",
      "poses": [
        "head1:orbit_m90",
        "head2:orbit_m90",
        "head3:orbit_m90",
        "head4:orbit_m90"
      ],
      "maxErrorDeg": 20.4,
      "severity": "significant"
    },
    {
      "caption": "Night",
      "poses": [
        "head1:orbit_m90",
        "head2:orbit_m90",
        "head3:orbit_m90",
        "head4:orbit_m90"
      ],
      "maxErrorDeg": 20.4,
      "severity": "significant"
    },
    {
      "caption": "Prowl",
      "poses": [
        "head1:orbit_m90",
        "head2:orbit_m90",
        "head3:orbit_m90",
        "head4:orbit_m90"
      ],
      "maxErrorDeg": 20.4,
      "severity": "significant"
    },
    {
      "caption": "Spiral",
      "poses": [
        "head1:orbit_m90",
        "head2:orbit_m90",
        "head3:orbit_m90",
        "head4:orbit_m90"
      ],
      "maxErrorDeg": 20.4,
      "severity": "significant"
    }
  ],
  "poseCaptions": [
    "Apex",
    "Apparition",
    "Ascension",
    "Ball Spiral",
    "Ball Wave",
    "Blink",
    "Build",
    "Canopy Ring",
    "Cathedral",
    "Circle",
    "Corner Chase",
    "Cross Weave",
    "Crowd Cascade",
    "Deep",
    "Diagonal Pulse",
    "Floor Bounce",
    "Floor Breathe",
    "Floor Cross",
    "Floor Ring",
    "Floor Wipe",
    "Freeze Frame",
    "Glitch",
    "Grand Sweep",
    "Idle",
    "Iris",
    "Landing",
    "Lazy Circle",
    "Neighbor Scan",
    "Night",
    "Peak",
    "Prowl",
    "Rise",
    "Slow Sweep",
    "Spiral",
    "Stutter",
    "Teleport",
    "Test Corner 1",
    "Test Corner 2",
    "Test Corner 3",
    "Test Corner 4",
    "To Ball",
    "To Crowd",
    "To Floor",
    "To Walls",
    "Wall Graze",
    "Warm Up",
    "Zenith"
  ],
  "colorCaptions": [
    "Blue",
    "Color Auto",
    "Color Drift",
    "Color Spin",
    "Cyan",
    "Deep",
    "Drop",
    "Duo Cyan/Pink",
    "Duo Green/Blue",
    "Green",
    "Idle",
    "Landing",
    "Night",
    "Orange",
    "Peak",
    "Pink",
    "Quad Spectrum",
    "Rainbow Wheel",
    "Red",
    "Spiral",
    "Split Pink/Green",
    "Split Red/Cyan",
    "Split Red/Green",
    "Split Warm/Cool",
    "Split White/Orange",
    "Split Yellow/Blue",
    "Sunset",
    "Warm Up",
    "Wheel Walk",
    "White",
    "White Bump",
    "Yellow"
  ]
};
