"""Generate `schemas/*.schema.json` from engine/config.py.

    python shared/tools/gen_schemas.py --write

The schemas exist so an editor can offer completion and inline errors while you
hand-edit `rig.json` at a venue -- VS Code picks them up from the `$schema` key
in each file, with no extension to install.

They are GENERATED rather than written, because the alternative is two
descriptions of the same file that agree on the day they are written and not
afterwards. `engine/config.py` is the one that runs the show, so it is the one
that is authoritative; this just translates it. CI regenerates and diffs, the
same way it does for the UI bundle.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO))

from engine import config as cfg           # noqa: E402
from engine import cues as cuesmod         # noqa: E402

OUT = REPO / "schemas"

SCHEMAS = {
    "venue": (cfg.VENUE, "A room: its size, the mirror ball, the crowd zone, "
                         "the canopy and truss, and the safety taper policy."),
    "rig": (cfg.RIG, "What is plugged in: fixtures, addresses, positions, tags, "
                     "and which room this event uses."),
    "calibration": (cfg.CALIBRATION, "What this rig measured in this room on "
                                     "this day: per head, the DMX that aims it "
                                     "at the ball."),
    "presets": (cfg.PRESETS, "Named combinations of the three slots, plus the "
                             "speed and master they were built at."),
    "looks": (cfg.LOOKS, "The look library, normally generated by "
                         "shared/tools/port_library.py."),
    "cues": (cuesmod.CUES_SCHEMA, "The night as an ordered list of cues, each "
                                  "filling the same three slots a preset does "
                                  "plus a fade and an optional hold, in beats."),
    "inventory": (cfg.INVENTORY, "Hardware actually owned. Events select from "
                                 "this; they never redefine hardware."),
}

_JSON_TYPES = {int: "integer", float: "number", str: "string", bool: "boolean",
               list: "array", dict: "object"}


def _types_of(spec: cfg.Spec) -> list[str]:
    if spec.types is object:
        return []
    types = spec.types if isinstance(spec.types, tuple) else (spec.types,)
    # int and float together is just "number" in JSON Schema; emitting both
    # makes an editor complain about `18288` being an integer where a float was
    # declared, which is not a thing JSON distinguishes.
    if set(types) == set(cfg.Number):
        return ["number"]
    return [_JSON_TYPES[t] for t in types if t in _JSON_TYPES]


def to_json_schema(spec: cfg.Spec) -> dict:
    node: dict = {}
    types = _types_of(spec)
    if types:
        node["type"] = types[0] if len(types) == 1 else types
    if spec.choices is not None:
        node["enum"] = list(spec.choices)
    if spec.min is not None:
        node["minimum"] = spec.min
    if spec.max is not None:
        node["maximum"] = spec.max
    if spec.non_empty:
        if "array" in types:
            node["minItems"] = 1
        elif "string" in types:
            node["minLength"] = 1
    if spec.fix:
        node["description"] = spec.fix
    if spec.of is not None:
        node["type"] = "object"
        node["properties"] = {k: to_json_schema(v) for k, v in spec.of.items()}
        required = [k for k, v in spec.of.items() if v.required]
        if required:
            node["required"] = required
    if spec.each is not None:
        node["type"] = "array"
        node["items"] = to_json_schema(spec.each)
    return node


def build(schema: dict[str, cfg.Spec], name: str, description: str) -> dict:
    properties = {k: to_json_schema(v) for k, v in schema.items()}
    properties["version"] = {
        "type": "integer",
        "description": f"Format version. Current is {cfg.CURRENT_VERSION}; "
                       f"a file with no version is treated as 1.",
    }
    # Every one of these files carries `_comment` arrays, and several carry keys
    # read by tools rather than by the engine. additionalProperties stays true
    # for the same reason the runtime validator ignores unknown keys: adding a
    # note to a file must not make an editor mark it broken.
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"https://github.com/cosmos-lights/schemas/{name}.schema.json",
        "title": f"cosmos {name}",
        "description": description,
        "type": "object",
        "properties": properties,
        "required": [k for k, v in schema.items() if v.required],
        "additionalProperties": True,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--write", action="store_true",
                        help="write the files; otherwise report drift only")
    args = parser.parse_args(argv)

    OUT.mkdir(exist_ok=True)
    drifted = []
    for name, (schema, description) in SCHEMAS.items():
        path = OUT / f"{name}.schema.json"
        text = json.dumps(build(schema, name, description), indent=2) + "\n"
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            print(f"  ok       {path.relative_to(REPO)}")
            continue
        drifted.append(path)
        if args.write:
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"  wrote    {path.relative_to(REPO)}")
        else:
            print(f"  DRIFTED  {path.relative_to(REPO)}")

    if drifted and not args.write:
        print("\nengine/config.py has changed since these were generated.\n"
              "  fix: python shared/tools/gen_schemas.py --write")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
